
version: '3'

services:
  nats-server:
    image: nats:latest

  client-gateway:
    build:
      context: ./client-gateway
      dockerfile: dockerfile.prod
    image: europe-southwest1-docker.pkg.dev/store-microservices-452520/image-registry/client-gateway
    ports:
      - ${CLIENT_GATEWAY_PORT}:${CLIENT_GATEWAY_PORT}
    environment:
      - PORT=${CLIENT_GATEWAY_PORT}
      - NATS_SERVERS=${NATS_SERVERS}


  products-service:
    build: 
      context: ./products-service
      dockerfile: dockerfile.prod
      args:
        - PRODUCTS_DB_URL=${PRODUCTS_DB_URL}
    image: europe-southwest1-docker.pkg.dev/store-microservices-452520/image-registry/products-service
    environment:
      - PORT=3000
      - NATS_SERVERS=${NATS_SERVERS}
      - DATABASE_URL=${PRODUCTS_DB_URL}

  orders-service:
    build: 
      context: ./orders-service
      dockerfile: dockerfile.prod
      args:
        - ORDERS_DB_URL=${ORDERS_DB_URL}
    image: europe-southwest1-docker.pkg.dev/store-microservices-452520/image-registry/orders-service
    environment:
      - PORT=3002
      - DATABASE_URL=${ORDERS_DB_URL}
      - NATS_SERVERS=${NATS_SERVERS}

  auth-service:
    build: 
      context: ./auth-service
      dockerfile: dockerfile.prod
    image: europe-southwest1-docker.pkg.dev/store-microservices-452520/image-registry/auth-service
    environment:
      - PORT=3007
      - NATS_SERVERS=${NATS_SERVERS}
      - DATABASE_URL=${AUTH_SERVICE_DB_URL}
      - JWT_SECRET=${JWT_SECRET}

  # =================
  # Payments Service
  # =================
    
  payments-service:
    build: 
      context: ./payments-service
      dockerfile: dockerfile.prod
    ports:
      - ${PAYMENTS_SERVICE_PORT}:3003
    image: europe-southwest1-docker.pkg.dev/store-microservices-452520/image-registry/payments-service
    environment:
      - PORT=${PAYMENTS_SERVICE_PORT}
      - NATS_SERVERS=${NATS_SERVERS}
      - STRIPE_API_KEY=${STRIPE_API_KEY}
      - SUCCESS_URL=${STRIPE_SUCCESS_URL}
      - CANCEL_URL=${STRIPE_CANCEL_URL}
      - ENDPOINT_SECRET=${STRIPE_ENDPOINT_SECRET}
